# Generated by Django 3.2.7 on 2021-09-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=255, null=True, verbose_name='age')),
                ('sex', models.CharField(blank=True, max_length=255, null=True, verbose_name='sex')),
                ('cp', models.CharField(blank=True, max_length=255, null=True, verbose_name=' chest pain type')),
                ('resting_bp', models.CharField(blank=True, max_length=255, null=True, verbose_name='resting blood pressure')),
                ('serum_cholesterol', models.CharField(blank=True, max_length=255, null=True, verbose_name='serum cholesterol')),
                ('fasting_blood_sugar', models.CharField(blank=True, max_length=255, null=True, verbose_name='fasting blood sugar')),
                ('resting_ecg', models.CharField(blank=True, max_length=255, null=True, verbose_name='resting ecg results ')),
                ('max_heart_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='max heart rate')),
                ('exercise_induced_angina', models.CharField(blank=True, max_length=255, null=True, verbose_name='exercise induced angina')),
                ('st_depression', models.CharField(blank=True, max_length=255, null=True, verbose_name='st depression')),
                ('st_slope', models.CharField(blank=True, max_length=255, null=True, verbose_name='slope of the peak exercise ST segment')),
                ('number_of_vessels', models.CharField(blank=True, max_length=255, null=True, verbose_name='number of Major vessels ')),
                ('thallium_scan_results', models.CharField(blank=True, max_length=255, null=True, verbose_name='thalassemia')),
            ],
        ),
    ]
